import uuid

MATERIALIZATION_RULE_VERSION = "phase3-plan-v1"
RUNTIME_REQUIREMENTS_VERSION = "phase3-runtime-requirements-v1"
ADDITION_REPEAT_POLICY_VERSION = "phase3-addition-repeat-policy-v1"
WAIVER_POLICY_VERSION = "phase3-waiver-v1"
MEASUREMENT_RULE_VERSION = "phase3-measurement-v1"
ADDITION_CORRECTION_VERSION = "phase3-addition-correction-v1"
OPERATION_SCHEMA_VERSION = "phase3-operation-v1"
LEGACY_SESSION_PROJECTION_VERSION = "legacy-phase1a-session-v1"
COMPLETION_AUDIT_VERSION = "phase3-completion-audit-v1"
JOURNAL_SCHEMA_VERSION = "phase3-journal-v1"

PLAN_IDENTITY_NAMESPACE = uuid.UUID("b3ad9f4c-9e5f-5a31-9df2-25d731f5a302")
LEGACY_IDENTITY_NAMESPACE = uuid.UUID("b3ad9f4c-9e5f-5a31-9df2-25d731f5a301")

NULL_SEQUENCE = 2147483647

CANONICAL_STAGES = (
    "PRE_BREW",
    "WATER_PREPARATION",
    "MILLING",
    "MASH_IN",
    "MASH",
    "LAUTER_SPARGE",
    "PRE_BOIL",
    "BOIL",
    "WHIRLPOOL_FLAMEOUT",
    "CHILL",
    "TRANSFER",
    "YEAST_PITCH",
    "BREW_COMPLETE",
)

CANONICAL_STAGE_RANK = {name: index * 10 + 10 for index, name in enumerate(CANONICAL_STAGES)}

SOURCE_KIND_RANK = {
    "EXPLICIT": 0,
    "DERIVED_CONDITIONAL": 1,
    "PHASE3_DEFAULT": 2,
    "LEGACY_PHASE1A": 2,
}

SUPPORTED_STEP_TYPES = {
    "MASH",
    "BOIL",
    "FERMENTATION_FOUNDATION",
    "PACKAGING_FOUNDATION",
}

REQUIRED_SESSION_STATES = ("PLANNED", "READY", "ACTIVE", "PAUSED", "COMPLETED", "ABORTED")
REQUIRED_STAGE_STATES = ("PENDING", "ACTIVE", "PAUSED", "COMPLETED", "SKIPPED", "ABORTED")
REQUIRED_TIMER_STATES = (
    "PENDING",
    "RUNNING",
    "PAUSED",
    "COMPLETED",
    "EXPIRED",
    "ACKNOWLEDGED",
    "CANCELLED",
)
REQUIRED_REMINDER_STATES = (
    "SCHEDULED",
    "DUE",
    "ACKNOWLEDGED",
    "COMPLETED",
    "SKIPPED",
    "CANCELLED",
    "EXPIRED",
)

ADDITION_REPEAT_POLICIES = ("NEVER", "PLANNED_OCCURRENCES_ONLY", "RUNTIME_REPEAT_ALLOWED")
TIMING_BASES = (
    "AT_STAGE_START",
    "FROM_STAGE_START",
    "BEFORE_PLANNED_STAGE_END",
    "AT_PLANNED_STAGE_END",
    "UNSCHEDULED",
)
CLOCK_BASES = ("WALL_CLOCK", "ACTIVE_TIME")

MEASUREMENT_TYPES = (
    "MASH_IN_TEMPERATURE",
    "MASH_REST_TEMPERATURE",
    "MASH_PH",
    "MASH_GRAVITY",
    "POST_MASH_GRAVITY",
    "PRE_BOIL_GRAVITY",
    "PRE_BOIL_VOLUME",
    "ORIGINAL_GRAVITY",
    "KNOCKOUT_VOLUME",
    "KNOCKOUT_TEMPERATURE",
    "PITCH_TEMPERATURE",
)

COMPARISON_STATUSES = (
    "WITHIN_TOLERANCE",
    "OUTSIDE_TOLERANCE",
    "MISSING",
    "NOT_APPLICABLE",
    "NO_TARGET",
    "WAIVED",
    "NOT_RECORDED",
)

OPTIONAL_STAGES = {"MILLING", "LAUTER_SPARGE"}
NONWAIVABLE_REQUIREMENT_KEYS = {
    "YEAST_PITCH_TIME",
    "YEAST_ADDITION_FACT",
    "PREFLIGHT_INTEGRITY",
}
