"""Imports all model modules for SQLAlchemy/Alembic metadata discovery."""

from brewing_api.domain.audit.models import AuditEvent, BrewJournalEvent
from brewing_api.domain.brew_day.models import (
    BrewAdditionCorrection,
    BrewAdditionEvent,
    BrewAttachment,
    BrewNote,
    BrewOperation,
    BrewPitchHandoff,
    BrewPlanStep,
    BrewReminderHistory,
    BrewRequirementTemplate,
    BrewStageRequirement,
    BrewTimerRevision,
    BrewWaiver,
)
from brewing_api.domain.brew_sessions.models import BrewSession, BrewStage, BrewTimer
from brewing_api.domain.equipment.models import EquipmentProfile
from brewing_api.domain.fermentation.models import (
    FermentationAction,
    FermentationAdditionCorrection,
    FermentationAdditionEvent,
    FermentationAdditionRequirement,
    FermentationDerivedGravitySnapshot,
    FermentationDeviation,
    FermentationJournalEvent,
    FermentationMeasurement,
    FermentationMeasurementCorrection,
    FermentationOgConsumption,
    FermentationOperation,
    FermentationPlanSnapshot,
    FermentationSession,
    FermentationStageInstance,
    FermentationWaiver,
    FermentationYeastPitchReference,
    PackagingReadinessHandoff,
)
from brewing_api.domain.identity.models import AuthSession, User
from brewing_api.domain.ingredients.models import Ingredient, IngredientLot, Supplier, SupplierItem
from brewing_api.domain.inventory.models import (
    InventoryLocation,
    InventoryReservation,
    InventoryTransaction,
    SafetyStockPolicy,
)
from brewing_api.domain.measurements.models import Deviation, Measurement
from brewing_api.domain.notifications.models import Notification
from brewing_api.domain.recipes.models import (
    IngredientSubstitution,
    Recipe,
    RecipeIngredient,
    RecipeProcessStep,
    RecipeVersion,
    WaterProfileTarget,
)

__all__ = [
    "AuditEvent",
    "AuthSession",
    "BrewAdditionCorrection",
    "BrewAdditionEvent",
    "BrewAttachment",
    "BrewJournalEvent",
    "BrewNote",
    "BrewOperation",
    "BrewPitchHandoff",
    "BrewPlanStep",
    "BrewReminderHistory",
    "BrewRequirementTemplate",
    "BrewSession",
    "BrewStage",
    "BrewStageRequirement",
    "BrewTimer",
    "BrewTimerRevision",
    "BrewWaiver",
    "Deviation",
    "EquipmentProfile",
    "FermentationAction",
    "FermentationAdditionCorrection",
    "FermentationAdditionEvent",
    "FermentationAdditionRequirement",
    "FermentationDerivedGravitySnapshot",
    "FermentationDeviation",
    "FermentationWaiver",
    "FermentationJournalEvent",
    "FermentationMeasurement",
    "FermentationMeasurementCorrection",
    "FermentationOgConsumption",
    "FermentationOperation",
    "FermentationPlanSnapshot",
    "FermentationSession",
    "FermentationStageInstance",
    "FermentationYeastPitchReference",
    "PackagingReadinessHandoff",
    "Ingredient",
    "IngredientLot",
    "IngredientSubstitution",
    "InventoryLocation",
    "InventoryReservation",
    "InventoryTransaction",
    "Measurement",
    "Notification",
    "Recipe",
    "RecipeIngredient",
    "RecipeProcessStep",
    "RecipeVersion",
    "SafetyStockPolicy",
    "Supplier",
    "SupplierItem",
    "User",
    "WaterProfileTarget",
]
